apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-all-pv
spec:
  storageClassName: mysql-all-sc
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: "192.168.231.241"
    path: "/nfs"
