apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-nfs-statefulset-0
spec:
  storageClassName: my-storage-class
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: nginx-nfs-pvc-nginx-nfs-statefulset-0
    namespace: nginx-nfs
  nfs:
    server: 192.168.231.241
    path: /nfs/nginx-pv1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-nfs-statefulset-1
spec:
  storageClassName: my-storage-class
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: nginx-nfs-pvc-nginx-nfs-statefulset-1
    namespace: nginx-nfs
  nfs:
    server: 192.168.231.241
    path: /nfs/nginx-pv2

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-nfs-statefulset-2
spec:
  storageClassName: my-storage-class
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: nginx-nfs-pvc-nginx-nfs-statefulset-2
    namespace: nginx-nfs
  nfs:
    server: 192.168.231.241
    path: /nfs/nginx-pv3
