apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "nginx-nfs-statefulset"
  namespace: nginx-nfs
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 33%
      maxSurge: 33%
  selector:
    matchLabels:
      app: nginx 
  serviceName: "nginx"
  replicas: 3 
  template:
    metadata:
      labels:
        app: nginx 
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: nginx:1.2
        ports: 
        - containerPort: 80
          name: "nginx"
        volumeMounts:
        - name: "nginx-nfs-pvc"
          mountPath: /var/www/html
  volumeClaimTemplates:
  - metadata:
      name: "nginx-nfs-pvc"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 3Gi
